services:
  - type: web
    name: telegram-site-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: CHAT_ID
        value: YOUR_CHAT_ID
